### ISSUE TITLE
Crash when launched via desktop

### ISSUE THREAD

**Issue by rafli-sss** [fdw/ranger-autojump#8]
Fedora 36 Gnome 42
Ranger version: ranger 1.9.3
Python version: 3.10.5 (main, Jun  9 2022, 00:00:00) [GCC 12.1.1 20220507 (Red Hat 12.1.1-1)]
Locale: en_US.UTF-8
[Video](https://user-images.githubusercontent.com/92916692/183093088-eb3ab5ac-76f5-4612-9760-be3280fc174f.webm)
[Screenshot](https://user-images.githubusercontent.com/92916692/183095038-92dc0ef9-4f73-4941-a319-f70447fb4a82.png)

**Comment by fdw** [comment]
If you launch it from the terminal, does the same thing happen?

Also, it seems from the screenshot that you do not have `autojump` installed (or not on the path). Could that be?

**Comment by rafli-sss** [comment]
> If you launch it from the terminal, does the same thing happen?
> 
> Also, it seems from the screenshot that you do not have `autojump` installed (or not on the path). Could that be?

1. It works when i launch it via terminal
2. When the plugin is deactivated, ranger works when i launch it via desktop
3. autojump --version
autojump v22.5.3
4. echo $PATH
/home/firstguardian/.autojump/bin:/home/firstguardian/bin:/home/firstguardian/.cargo/bin:/home/firstguardian/.local/bin:/usr/local/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/firstguardian/.composer/vendor/bin

**Comment by fdw** [comment]
I would guess that you add `/home/firstguardian/.autojump/bin` to your path in one of your shell's rc files, right? So, when you start `ranger` from there, the files have been read, the path has been added, at it works.
But if you start it directly, then the path is not added (as you haven't started the shell first), which crashes the plugin.

Can you install `autojump` globally, via your distro, so that you don't need to add the path first? Otherwise, you need to find a way to add that path without involving the shell.

**Comment by rafli-sss** [comment]
Thanks, it works!!!
